services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: aipyq:latest  # 使用已加载的镜像
    container_name: Chizhou-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - vectordb
      # - rag_api  # 如果 RAG 镜像不可用，可以注释掉这行
    restart: always
    networks:
      - aipyq-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/Aipyq
      - MEILI_HOST=http://meilisearch:7700
      # - RAG_PORT=${RAG_PORT:-8000}  # 如果禁用 RAG，注释这些
      # - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./Aipyq.yaml
        target: /app/Aipyq.yaml
      # specs 已包含在镜像中，不需要 volume mount
      # - ./specs:/app/specs
      # images 是运行时数据（用户上传），保留 volume mount
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

  client:
    image: nginx:1.27.0-alpine
    container_name: Chizhou-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    networks:
      - aipyq-network
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      
  mongodb:
    container_name: pyqchat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    networks:
      - aipyq-network
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    networks:
      - aipyq-network
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:  # PG向量数据库，主要用于 RAG
    container_name: chizhou-vectordb
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    networks:
      - aipyq-network
    volumes:
      - pgdata-aipyq:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  # rag_api:  # 如果镜像不可用或不需要 RAG 功能，可以注释掉整个服务
  #   image: ghcr.io/constanji/aipyq-rag-api-dev-lite:latest
  #   environment:
  #     - DB_HOST=vectordb
  #     - RAG_PORT=${RAG_PORT:-8000}
  #   restart: always
  #   depends_on:
  #     - vectordb
  #   env_file:
  #     - .env

networks:
  aipyq-network:
    driver: bridge

volumes:
  pgdata-aipyq:  # 使用独立的卷名，避免与BecauseCha冲突
