# 本地完整部署配置 - 避免与 chizhou-local-dev 冲突
# 使用方法: docker compose -f deploy-compose.local.yml up -d

services:
  api:
    image: chizhou:latest  # 使用已加载的镜像
    container_name: Chizhou-API-Local
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - vectordb
    restart: always
    networks:
      - chizhou-deploy-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096 --expose-gc
      - MONGO_URI=mongodb://mongodb:27017/Chizhou
      - MEILI_HOST=http://meilisearch:7700
      - CONFIG_PATH=/app/Chizhou.yaml
      # 向量数据库配置（必须在 environment 中显式设置，env_file 可能不会覆盖）
      - VECTOR_DB_HOST=vectordb
      - VECTOR_DB_PORT=5432
      - VECTOR_DB_NAME=Chizhou
      - VECTOR_DB_USER=Chizhou
      - VECTOR_DB_PASSWORD=Chizhou
    volumes:
      - type: bind
        source: ./Chizhou.yaml
        target: /app/Chizhou.yaml
      # specs 已包含在镜像中，不需要 volume mount
      # - ./specs:/app/specs
      # images 是运行时数据（用户上传），保留 volume mount
      # 使用不同的目录避免与 local-dev 冲突
      - ./images-deploy:/app/client/public/images
      - ./uploads-deploy:/app/uploads
      - ./logs-deploy:/app/api/logs

  client:
    image: nginx:1.27.0-alpine
    container_name: Chizhou-NGINX-Local
    ports:
      - 8080:80  # 使用 8080 避免与常用端口冲突
      - 8443:443
    depends_on:
      - api
    restart: always
    networks:
      - chizhou-deploy-network
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      
  mongodb:
    container_name: chizhou-mongodb-deploy  # 不同的容器名
    image: mongo
    restart: always
    networks:
      - chizhou-deploy-network
    volumes:
      # 使用不同的数据目录避免与 local-dev 冲突
      - ./data-node-deploy:/data/db
    command: mongod --noauth
    # 不映射端口到宿主机，只在容器网络内使用
    
  meilisearch:
    container_name: chizhou-meilisearch-deploy  # 不同的容器名
    image: getmeili/meilisearch:v1.12.3
    restart: always
    networks:
      - chizhou-deploy-network
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      # 使用不同的数据目录避免与 local-dev 冲突
      - ./meili_data_deploy:/meili_data
    # 不映射端口到宿主机，只在容器网络内使用
    
  vectordb:  # PG向量数据库，主要用于 RAG
    container_name: chizhou-vectordb-deploy  # 不同的容器名
    image: pgvector/pgvector:0.8.0-pg15-trixie
    ports:
      - "5235:5432"  # 使用 5235 避免与 local-dev 的 5234 冲突
    environment:
      POSTGRES_DB: Chizhou
      POSTGRES_USER: Chizhou
      POSTGRES_PASSWORD: Chizhou
    restart: always
    networks:
      - chizhou-deploy-network
    volumes:
      - pgdata-chizhou-deploy:/var/lib/postgresql/data  # 不同的卷名
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Chizhou -d Chizhou"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  chizhou-deploy-network:  # 不同的网络名
    driver: bridge

volumes:
  pgdata-chizhou-deploy:  # 不同的卷名，避免与 local-dev 冲突
